name: Build

on:
  - push
  - pull_request
  - release

jobs:
  build:
    runs-on: ubuntu-22.04
    container: postgres:15.6-alpine
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15.6-alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - run: apk add --no-cache git python3 curl xz
    - uses: actions/checkout@v3.6.0
    #- uses: actions/setup-python@v4.0.0
    #  with:
    #    python-version: '3.11'
    # We'll set the -f flag is we're not in the "main" branch
    - run: ./build.py -H postgres ${{ github.ref != 'refs/heads/main' && '-f' || '' }}
    - uses: xresloader/upload-to-github-release@v1.6.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        file: "*.xz"
        tags: true
        draft: true
